### ISSUE TITLE
SyntaxError: Unexpected token )

### ISSUE THREAD

**Issue by filipemeneses** [albinekb/favicon-emoji#8]
Syntax error when running `favicon-emoji --emoji ⚔️`

```
/Users/filipe/.nvm/versions/node/v7.10.1/lib/node_modules/favicon-emoji/cli.js:68
        )
        ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
```

```
/Users/filipe/.nvm/versions/node/v7.10.1/lib/node_modules/favicon-emoji/lib/browser.js:70
    )
    ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/filipe/.nvm/versions/node/v7.10.1/lib/node_modules/favicon-emoji/lib/render.js:3:29)
```

I fixed locally by removing the unnecessary `,`

mac: 10.12.6
npm: v4.2.0
node: v7.10.1

**Comment by maml** [comment]
Issue appears beginning with `v2.0.0`

`v1.0.4` seems to be the most recent working version.

**Comment by albinekb** [comment]
Hi! It appears to be an issue with you running an outdated version of chrome that does not support trailing comma, I'll update the lib in a second

**Comment by albinekb** [comment]
Fixed and released, please try again 🙏  Upgrade 
`npm install --global favicon-emoji`
`yarn gobal add favicon-emoji`

Make sure you have chrome installed as it uses it to generate the files 👍  I'll add checks for this later

**Comment by albinekb** [comment]
After looking at it again, it seems like node 7.10 does not support trailing comma in function params, but this should work now, let me know 👍  If this library gets more use we could add some tests

**Comment by filipemeneses** [comment]
Reinstalled:
```
npm uninstall --global favicon-emoji
npm install --global favicon-emoji
```

and not working:
```
$ favicon-emoji --help
/Users/filipe/.nvm/versions/node/v7.10.1/lib/node_modules/favicon-emoji/cli.js:68
        ),
        ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9
```

**Comment by albinekb** [comment]
I'm so sorry @filipemeneses update again and it'll work  🙈   I added tests and the standard linter and tested on node 7.10 now 🙏

**Comment by albinekb** [comment]
@filipemeneses did you get it working? 🤓
